# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"h\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\r\n\x05image\x18\x06 \x01(\t\"2\n\x0bProductList\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.products.Product\"\x14\n\x12ProductListRequest\"/\n\x08Wishlist\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.products.Product\"\x11\n\x0fWishlistRequest\"\"\n\x14\x41\x64\x64ToWishlistRequest\x12\n\n\x02id\x18\x01 \x01(\t\"M\n\x15\x41\x64\x64ToWishlistResponse\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.products.Product\x12\x0f\n\x07isExist\x18\x02 \x01(\x08\"\'\n\x19RemoveFromWishlistRequest\x12\n\n\x02id\x18\x01 \x01(\t\"R\n\x1aRemoveFromWishlistResponse\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.products.Product\x12\x0f\n\x07isExist\x18\x02 \x01(\x08\"\x18\n\x16\x43heckConnectionRequest\"*\n\x17\x43heckConnectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9d\x03\n\x0eProductService\x12V\n\x0f\x43heckConnection\x12 .products.CheckConnectionRequest\x1a!.products.CheckConnectionResponse\x12\x42\n\x0bGetProducts\x12\x1c.products.ProductListRequest\x1a\x15.products.ProductList\x12<\n\x0bGetWishList\x12\x19.products.WishlistRequest\x1a\x12.products.Wishlist\x12P\n\rAddToWishlist\x12\x1e.products.AddToWishlistRequest\x1a\x1f.products.AddToWishlistResponse\x12_\n\x12RemoveFromWishlist\x12#.products.RemoveFromWishlistRequest\x1a$.products.RemoveFromWishlistResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=28
  _globals['_PRODUCT']._serialized_end=132
  _globals['_PRODUCTLIST']._serialized_start=134
  _globals['_PRODUCTLIST']._serialized_end=184
  _globals['_PRODUCTLISTREQUEST']._serialized_start=186
  _globals['_PRODUCTLISTREQUEST']._serialized_end=206
  _globals['_WISHLIST']._serialized_start=208
  _globals['_WISHLIST']._serialized_end=255
  _globals['_WISHLISTREQUEST']._serialized_start=257
  _globals['_WISHLISTREQUEST']._serialized_end=274
  _globals['_ADDTOWISHLISTREQUEST']._serialized_start=276
  _globals['_ADDTOWISHLISTREQUEST']._serialized_end=310
  _globals['_ADDTOWISHLISTRESPONSE']._serialized_start=312
  _globals['_ADDTOWISHLISTRESPONSE']._serialized_end=389
  _globals['_REMOVEFROMWISHLISTREQUEST']._serialized_start=391
  _globals['_REMOVEFROMWISHLISTREQUEST']._serialized_end=430
  _globals['_REMOVEFROMWISHLISTRESPONSE']._serialized_start=432
  _globals['_REMOVEFROMWISHLISTRESPONSE']._serialized_end=514
  _globals['_CHECKCONNECTIONREQUEST']._serialized_start=516
  _globals['_CHECKCONNECTIONREQUEST']._serialized_end=540
  _globals['_CHECKCONNECTIONRESPONSE']._serialized_start=542
  _globals['_CHECKCONNECTIONRESPONSE']._serialized_end=584
  _globals['_PRODUCTSERVICE']._serialized_start=587
  _globals['_PRODUCTSERVICE']._serialized_end=1000
# @@protoc_insertion_point(module_scope)
